; ============================================================
;  ATmega1284P + MightyCore
;  - interní oscilátor 8 MHz
;  - UART0 bootloader (Optiboot)
;  - 2 prostředí: ISP + UART
; ============================================================

[env]
platform = atmelavr
framework = arduino
board = ATmega1284P

; MightyCore
board_build.core = MightyCore
board_build.f_cpu = 1000000L
board_hardware.oscillator = internal
board_hardware.uart = uart0
board_hardware.bod = 2.7v
board_hardware.eesave = yes
board_bootloader.type = optiboot

; Build flags
build_flags =
  -DARDUINO_AVR_ATmega1284P

; Knihovny
lib_deps =
  wire
  adafruit/RTClib@^2.1.1


; =========================
; 1) ISP / STK500 (programátor)
; =========================
[env:ATmega1284P_isp]
extends = env


upload_protocol = stk500v2
upload_port = /dev/ttyUSB0
upload_speed = 9600

upload_flags =
  -P/dev/ttyUSB0
  -b115200
  -cstk500v2


; =========================
; 2) UART bootloader (Optiboot) přes UART0
; =========================
[env:ATmega1284P_uart]
extends = env

upload_protocol = arduino
upload_port = /dev/ttyUSB0
upload_speed = 9600

monitor_port = /dev/ttyUSB0
monitor_speed = 2400
